### ISSUE TITLE
add CLI logging level option

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandidav#69]
ATM `dandidav` is very talkative.  I would not be surprised if that somehow also affects performance (ref #54) since it is processing lots of requests in parallel and screen is very busy with logs. Would be great to be able to reduce logging level to WARNING or alike.  

<details>
<summary>"Current" options</summary> 

```shell
shub@falkor:~/dandidav-test$ ./dandidav --help
WebDAV view to DANDI Archive

See <https://github.com/dandi/dandidav> for more information.

Usage: dandidav [OPTIONS]

Options:
      --api-url <URL>
          API URL of the DANDI Archive instance to serve
          
          [default: https://api.dandiarchive.org/api]

      --ip-addr <IP_ADDR>
          IP address to listen on
          
          [default: 127.0.0.1]

  -p, --port <PORT>
          Port to listen on
          
          [default: 8080]

  -T, --title <TITLE>
          Site name to include in HTML page titles
          
          [default: dandidav]

  -h, --help
          Print help (see a summary with '-h')

  -V, --version
          Print version
shub@falkor:~/dandidav-test$ ./dandidav --version
dandidav 0.1.0 (commit: c2195f4)

```
</details>

**Comment by jwodder** [comment]
@yarikoptic If you're still using commit c2195f4, you don't have the updates from #58, which drastically reduced the amount of stuff logged.  Try updating and then see how you like the logs.

**Comment by yarikoptic** [comment]
Let's close for now -- I don't think I was burdened with them recently
