### ISSUE TITLE
Provide JSON content-type for JSON files within zarrs

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandidav#90]
the goal is to be able to navigate/view those files conveniently in the browser

```shell
❯ file -L .zattrs
.zattrs: JSON text data
❯ file -L .zgroup
.zgroup: JSON text data
❯ file -L .zmetadata
.zmetadata: JSON text data
```

according to https://zarr.readthedocs.io/en/stable/spec/v2.html#hierarchies -- should be JSONs

**Comment by jwodder** [comment]
@yarikoptic If you mean that you want the browser to treat the files as JSON when clicking on the file links, that would require S3 to send the proper Content-Type header.  This would require either setting the Content-Type for the files directly on S3 or else generating a signed download URL that sets the Content-Type (which requires having access to the S3 credentials).

**Comment by yarikoptic** [comment]
RIGHT, I forgot that we are just forwarding here! 
BTW -- if it is possible to set content-type on S3 -- we should probably do that during upload. Can we do that?

**Comment by jwodder** [comment]
@yarikoptic I think that setting the Content-Type during upload would require the same Content-Type to be specified when creating the signed upload URL, so the client would have to send a Content-Type when requesting the upload URLs from the Archive, the Archive would have to include the field when generating the upload URLs, and then I think the client would have to specify the Content-Type again when doing the actual upload.

**Comment by yarikoptic** [comment]
cool, so it should then be done on the level of dandi-archive... we already have a dedicated procedure etc for upload of zarrs, so should be doable via consideration of filenames (zarr v3 I believe would even have `zarr.json` instead of `.zarray`, `.zgroup` and `.zattrs`) while preparing the upload.  Could you please research/come up with an example to demonstrate it and open an issue (or a PR) in dandi-archive to close this one?

**Comment by jwodder** [comment]
@yarikoptic 

> Could you please research/come up with an example to demonstrate it

What exactly are you asking for?  What is the issue supposed to demonstrate?

**Comment by yarikoptic** [comment]
If it is possible to mint S3 upload URL so that after file uploaded, the http url for download from S3 would have content-type of JSON so browsers would be able to display it nicely, instead of just requesting to download how it is now for `.zattrs` etc JSON files.

**Comment by jwodder** [comment]
@yarikoptic I can't demonstrate anything without S3 credentials, so I just filed a normal feature request: https://github.com/dandi/dandi-archive/issues/1870

**Comment by jwodder** [comment]
Closing as this is an Archive problem.
